In [229]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [231]:
dataset = pd.read_csv("Ecommerce Customers")

In [233]:
dataset.head()

Email  \
0      mstephenson@fernandez.com   
1              hduke@hotmail.com   
2               pallen@yahoo.com   
3        riverarebecca@gmail.com   
4  mstephens@davidson-herman.com   

                                             Address            Avatar  \
0       835 Frank Tunnel\nWrightmouth, MI 82180-9605            Violet   
1     4547 Archer Common\nDiazchester, CA 06566-8576         DarkGreen   
2  24645 Valerie Unions Suite 582\nCobbborough, D...            Bisque   
3   1414 David Throughway\nPort Jason, OH 22070-1220       SaddleBrown   
4  14023 Rodriguez Passage\nPort Jacobville, PR 3...  MediumAquaMarine   

   Avg. Session Length  Time on App  Time on Website  Length of Membership  \
0            34.497268    12.655651        39.577668              4.082621   
1            31.926272    11.109461        37.268959              2.664034   
2            33.000915    11.330278        37.110597              4.104543   
3            34.305557    13.717514        36.721283              3.120179   
4            33.330673    12.795189        37.536653              4.446308   

   Yearly Amount Spent  
0           587.951054  
1           392.204933  
2           487.547505  
3           581.852344  
4           599.406092

In [235]:
dataset = dataset.drop(columns = ["Email","Avatar","Address"])

In [237]:
dataset.head()

Avg. Session Length  Time on App  Time on Website  Length of Membership  \
0            34.497268    12.655651        39.577668              4.082621   
1            31.926272    11.109461        37.268959              2.664034   
2            33.000915    11.330278        37.110597              4.104543   
3            34.305557    13.717514        36.721283              3.120179   
4            33.330673    12.795189        37.536653              4.446308   

   Yearly Amount Spent  
0           587.951054  
1           392.204933  
2           487.547505  
3           581.852344  
4           599.406092

In [239]:
#let's normalize the data
dataset = ( dataset - dataset.min() ) / ( dataset.max()  - dataset.min() )

In [241]:
dataset.head()

Avg. Session Length  Time on App  Time on Website  Length of Membership  \
0             0.751425     0.626620         0.929816              0.573101   
1             0.362306     0.393016         0.550801              0.359869   
2             0.524953     0.426378         0.524803              0.576396   
3             0.722409     0.787050         0.460890              0.428434   
4             0.574861     0.647702         0.594748              0.627768   

   Yearly Amount Spent  
0             0.651040  
1             0.266355  
2             0.453725  
3             0.639055  
4             0.673552

In [243]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Avg. Session Length   500 non-null    float64
 1   Time on App           500 non-null    float64
 2   Time on Website       500 non-null    float64
 3   Length of Membership  500 non-null    float64
 4   Yearly Amount Spent   500 non-null    float64
dtypes: float64(5)
memory usage: 19.7 KB


In [245]:
#okay so there no nAn values

In [247]:
y = dataset["Yearly Amount Spent"]
X = dataset

In [249]:
X = X.drop(columns = ["Yearly Amount Spent"])

In [251]:
X.head()

Avg. Session Length  Time on App  Time on Website  Length of Membership
0             0.751425     0.626620         0.929816              0.573101
1             0.362306     0.393016         0.550801              0.359869
2             0.524953     0.426378         0.524803              0.576396
3             0.722409     0.787050         0.460890              0.428434
4             0.574861     0.647702         0.594748              0.627768

In [253]:
from sklearn.model_selection import train_test_split

In [255]:
X_train,X_test,y_train,y_test = train_test_split(X , y , test_size = 0.3 , random_state=43)

In [257]:
#let's convert our pandas series/dataframe into numpy array for the calculus  

In [259]:
X = X.to_numpy()

In [261]:
X.shape

(500, 4)

In [263]:
y = y.to_numpy()

In [265]:
y.shape # a scalar

(500,)

In [267]:
y.size

500

In [269]:
def model(X , y , learning_rate , iteration):
    m = y.size
    theta = np.zeros((X.shape[1],1))
    cost_list = []
    
    for i in range(iteration):
        
        y_pred = np.dot(X,theta)
        cost = (1/(2*m))*np.sum(np.square(y_pred - y))

        d_theta = (1/m)*np.dot(X.T , y_pred - y)
        theta  = theta - learning_rate*d_theta
        cost_list.append(cost)
        
    return theta,cost_list

In [271]:
y_train = y_train.to_numpy()
y_test = y_test.to_numpy()

In [273]:
y_train = y_train.reshape(-1, 1)
y_test = y_test.reshape(-1, 1)

In [275]:
learning_rate_bis = 0.05
iteration_bis = 1000

In [277]:
theta,cost_list = model(X_train , y_train , learning_rate_bis , iteration_bis )

In [282]:
predictions = np.dot(X_test,theta)

In [284]:
predictions

array([[0.3676603 ],
       [0.4424892 ],
       [0.52130945],
       [0.62705089],
       [0.60638467],
       [0.38780204],
       [0.67914832],
       [0.44926352],
       [0.39063054],
       [0.46676333],
       [0.61823393],
       [0.52202326],
       [0.4341207 ],
       [0.4351965 ],
       [0.40195671],
       [0.5673891 ],
       [0.46138849],
       [0.373541  ],
       [0.48250779],
       [0.49473859],
       [0.44482916],
       [0.49100661],
       [0.39859936],
       [0.37640152],
       [0.57991308],
       [0.42413329],
       [0.45702527],
       [0.44121964],
       [0.45535473],
       [0.52662102],
       [0.36089841],
       [0.41099612],
       [0.62983804],
       [0.55957016],
       [0.47731223],
       [0.54002412],
       [0.33711828],
       [0.46445841],
       [0.43387121],
       [0.49963189],
       [0.47315642],
       [0.47383337],
       [0.48820912],
       [0.50764877],
       [0.62541638],
       [0.38230661],
       [0.45094351],
       [0.360

In [286]:
y_test

array([[0.29681555],
       [0.41618559],
       [0.53279659],
       [0.66770366],
       [0.70783618],
       [0.26960275],
       [0.79346818],
       [0.43130506],
       [0.30528249],
       [0.41788575],
       [0.73784921],
       [0.55253193],
       [0.38410702],
       [0.47389673],
       [0.38303216],
       [0.56547094],
       [0.42584419],
       [0.28593327],
       [0.46268144],
       [0.45374047],
       [0.40729841],
       [0.44611118],
       [0.29649644],
       [0.2599401 ],
       [0.62332353],
       [0.36028875],
       [0.46585359],
       [0.40308738],
       [0.4251205 ],
       [0.58432495],
       [0.2816427 ],
       [0.33033852],
       [0.70144488],
       [0.59140991],
       [0.49271991],
       [0.55439821],
       [0.25087159],
       [0.44445582],
       [0.35694975],
       [0.49883454],
       [0.4508476 ],
       [0.48443653],
       [0.49536447],
       [0.49543554],
       [0.66651011],
       [0.38313617],
       [0.43683158],
       [0.299

In [298]:
from sklearn.metrics import mean_absolute_error
print("mean absolute error",mean_absolute_error(y_test,predictions))
print("values of theta:\n",theta)

mean absolute error 0.04839062259902078
values of theta:
 [[ 0.18030909]
 [ 0.29756164]
 [-0.04594479]
 [ 0.51722296]]
